env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  [
    "eslint:recommended",
    "prettier",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:unicorn/recommended",
  ]
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    experimentalDecorators: true
    jsx: true
  sourceType: module
  project: "./tsconfig.withTests.json"
  ecmaVersion: 2018
plugins:
  - unused-imports
  - unicorn
rules:
  radix: error
  eqeqeq: error
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-non-null-assertion": off
  semi: ["error", "always"]
  "@typescript-eslint/no-unused-vars": "off"
  "unused-imports/no-unused-imports": "error"
  "unused-imports/no-unused-vars":
    [
      "warn",
      {
        "vars": "all",
        "varsIgnorePattern": "^_",
        "args": "after-used",
        "argsIgnorePattern": "^_",
      },
    ]
  "unicorn/filename-case": "off"
  "unicorn/prevent-abbreviations": "off"
