name: CI
on: [push, pull_request_target]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          CI: true

      - name: Lint
        run: pnpm run lint
        env:
          CI: true
      
      - name: Setup Test Database
        run: docker compose up -d
        env:
          CI: true
      
      - name: Test
        run: pnpm run test --ci --coverage --maxWorkers=2
        env:
          CI: true

      - name: Build
        run: pnpm run build
        env:
          CI: true
