name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          CI: true

      - name: Lint
        run: pnpm lint
        env:
          CI: true
      
      - name: Setup Test Database
        run: docker-compose up -d
        env:
          CI: true
      
      - name: Test
        run: pnpm test --ci --coverage --maxWorkers=2
        env:
          CI: true

      - name: Build
        run: pnpm build
        env:
          CI: true
